credentials:
  path: ./credentials.yaml
launch:
  install-hdfs: true
  install-spark: true
  name: demo-cluster
  num-slaves: 1
  password: change-me-321
providers:
  ec2:
    ami: ami-e12ac3f7
    availability-zone: us-east-1b
    instance-initiated-shutdown-behavior: terminate
    instance-type: r3.2xlarge
    region: us-east-1
    spot-price: 1.0
    user: ec2-user
services:
  hdfs:
    version: 2.7.4
  spark:
    version: 2.1.0
