ipython:
    config-file: /root/.ipython/profile_default/ipython_config.py
    notebook-config-file: /root/.ipython/profile_default/ipython_notebook_config.py

spark:
    conf-file: /root/spark/conf/spark-defaults.conf
